### ISSUE TITLE
Feature request: Don't highlight illegal relation symbols.

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/language-argdown#1]
In view of the following:

"Folgendes ist deswegen momentan nicht möglich:

```A statement
  + First argument
      - Second argument
      - Third argument

  - Fourth argument
```

Die Leerzeile vor dem vierten Argument beendet den Argdown-Block. Danach wird ein neuer Argdown-Block mit einer Relation begonnen, die sich auf nichts bezieht, was zu einem Parser-Fehler führt."

I suggest that illegal relations symbols (e.g. the "-" before "Fourth argument" above) not be colored. If only legal relations symbols were colored, users could see that something's wrong while editing.

**Comment by christianvoigt** [comment]
See my comment on #7

Syntax errors will be visualized by a code linter that is completely separate from the code highlighting.
