### ISSUE TITLE
Feature request: Don't highlight illegal premiss-conclusion lists

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/language-argdown#2]
Argdown will not recognize premiss-conclusion lists (i) if they immediately follow, without blank line, an argument description or (ii) if they are attached to a relation. E.g., the following throws a parser error:
```
<Argument 1>: Argument 1.
(1) P1
(2) P2
----
(3) C
```
And here, the premiss-conclusion structure is not associated with <Argument 1>:
```
[T]: Central claim.
  <+ <Argument 1>: Argument 1.

    (1) P1
    (2) P2
    ----
    (3) C
```
My suggestion: In both cases (as well as in other cases where the premiss-conclusion list is illegal), the list should not be highlighted / colored.

**Comment by christianvoigt** [comment]
See my comment on #7 

Syntax errors will be visualized by a code linter that is completely separate from the code highlighting.
