### ISSUE TITLE
Folding

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/language-argdown#4]
It would be very useful if [folding capability](https://en.wikipedia.org/wiki/Folding_editor) were supported for the following argdown elements in Atom:

1. Fold / unfold entire sections, subsections etc.
2. Fold / unfold descriptions of statements and arguments
3. Fold / unfold premiss-conclusion structures
4. Fold / unfold inference patterns
5. Fold / unfold subtrees in a pro / con reasons hierarchy

**Comment by ggbetz** [comment]
Folding works, e.g., great for json in Atom.

**Comment by christianvoigt** [comment]
Folding usually works by defining start and end patterns. For example this is how folding in VS Code works. Markdown and Argdown are not suited for this as there is no explicit "end section" token. Sections end if new sections begin. A workaround would be a specific syntax for defining regions, simlar to C# regions (#region, #endregion) just for this purpose. But I don't think that is a good idea. So I am closing this for now.
