### ISSUE TITLE
Syntax highlight of inference pattern

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/language-argdown#7]
``` 
(3) Was inakzeptable Folgen hat, ist unzulässig.
--[Mit S (aus 1,2,3)]--
(4) Moderne Massentierhaltung ist unzulässig.
```
wird als korrekter Code gehighlighted, wirft aber Fehler.

**Comment by christianvoigt** [comment]
In general the code highlighting is much simpler minded than the real parser and it will never detect every syntax error possible. It is not the job of the code highlighting to detect such errors. This is the job of a linter plugin that is based on the real Argdown Parser. The job of the syntax highlighting is only to make the Argdown code look nice.
