### ISSUE TITLE
Editor doesn't allow me to use the full div width for the text

### ISSUE THREAD

**Issue by rapus95** [christianvoigt/language-argdown#9]
![image](https://user-images.githubusercontent.com/5960902/37247780-1bb884c8-24c1-11e8-9f63-729c9dc66dbc.png)
As you can see I'm not allowed to use the full width :(

**Comment by christianvoigt** [comment]
Yes, sorry about that, it was an intentional feature... 
Please note that we switched to VS Code. Our VS Code extension does not have a width restriction and allows you to export argdown files to dot, json and html (more formats coming soon).

**Comment by rapus95** [comment]
Meanwhile I switched aswell 😁
